// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3D_Marketplace.Models;

#nullable disable

namespace _3D_Marketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725011449_AddingIsPublished")]
    partial class AddingIsPublished
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_3D_Marketplace.Models.ProductData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmbientOcclusion")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("BaseColor")
                        .HasColumnType("varchar(500)");

                    b.Property<float>("CameraDefaultZPos")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(3500)");

                    b.Property<string>("Emission")
                        .HasColumnType("varchar(500)");

                    b.Property<float>("Emission_Brightness")
                        .HasColumnType("real");

                    b.Property<string>("Emission_Color")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.Property<string>("HDRI")
                        .HasColumnType("varchar(500)");

                    b.Property<float>("HDRI_Brightness")
                        .HasColumnType("real");

                    b.Property<bool>("HDRI_ShowAsBackground")
                        .HasColumnType("bit");

                    b.Property<string>("Metallic")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NormalMap")
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Roughness")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("ViewDefaultRotation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isPublished")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("_3D_Marketplace.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_3D_Marketplace.Models.ProductData", b =>
                {
                    b.HasOne("_3D_Marketplace.Models.UserData", "Seller")
                        .WithMany("products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("_3D_Marketplace.Models.UserData", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
